### ISSUE TITLE
More detailed instruction for getting NYT Token?

### ISSUE THREAD

**Issue by nikhgarg** [kesyog/crossword#6]
Hi, I'm not sure I understand exactly how to get my token. I've done inspect > network on Chrome, but there are many lines that come out when I load a crossword. What exactly should I look for to get my NYT token?

**Comment by kesyog** [comment]
I'll work on beefing up the instructions, but for now (using Chrome):

1. Open the Network tab in Developer Options
2. Open <https://www.nytimes.com/crosswords>
3. Find a request for some kind of json file. e.g. `progress.json`, `mini-stats.json`, or `stats-and-streaks.json`
4. In the headers pane, find the value of `nyt-s` in the list of request headers. That is your token.

**Comment by nikhgarg** [comment]
Thank you, that worked!
