### ISSUE TITLE
It looks like this has stopped working?

### ISSUE THREAD

**Issue by jsundram** [kesyog/crossword#9]
I've had this on cron to run monthly, but it hasn't gotten any new data since my pull on September 1; has the underlying API changed?

The curl request posted in the [README](https://github.com/kesyog/crossword/blob/main/README.md) currently fails, e.g. 

`curl 'https://nyt-games-prd.appspot.com/svc/crosswords/v3/36569100/puzzles.json?publish_type=daily&date_start=2023-09-01&date_end=2023-10-01' -H 'accept: application/json'`

returns 
```html
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Access is forbidden.</h2>
<h2></h2>
</body></html>
```

when I run `./target/release/crossword data.csv  --token {my token} --start-date 2023-09-01`

I get:
```txt
Fetching NYT crossword stats since 2023-09-01
▕⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛▏0s 100% 🎉 All done after 1 requests
```

however, data.csv is empty. I've logged in to the website and updated my nyt-s token (it's now NYT-S, and the value seems to have changed since I last cached it) but that doesn't seem to make a difference.

**Comment by kesyog** [comment]
I double-checked my CSV file and the most recent puzzle it has data for is from 2023-09-27. I'll take a look soon to see if I can find a replacement API. Feel free to take a look if you've got the spare time.

**Comment by kesyog** [comment]
Was able to fix by updating the endpoint URL, following https://www.reddit.com/r/crossword/comments/16uk92h/nyt_crossword_api_endpoint_downmoved/. Thanks for the heads up!

**Comment by jsundram** [comment]
Thanks so much for the quick fix!
